### ISSUE TITLE
Make the project go-get-able by using an idiomatic directory structure

### ISSUE THREAD

**Issue by peterbourgon** [gleicon/habitat#1]
`go get github.com/gleicon/habitat`

Expected behavior: `habitat` is placed into my $GOPATH/bin

Actual behavior: "no buildable Go source files in …/src/github.com/gleicon/habitat"

---

Move *.go from the `src` subdirectory to the main directory, and `rmdir src`. I think that should do it.

**Comment by gleicon** [comment]
Hi, I just saw this issue now. Would you care to send a pull request ? Apparently I'm messing up something by trying what you proposed. I've moved sources and even them it's complaining a bit... If you do that make sure you put your name on CONTRIBUTORS file. Thanks for the time looking at it :D

**Comment by gleicon** [comment]
@fiorix helped fix it, I think I've botched b/c my old golang install came from brew. Thanks !
